import streamlit as st

from utils.data_loader import load_data
from utils.theme import inject_css
from utils.components import page_header, banner
from utils.state import render_global_filters
from utils.insights import generate_summary

st.set_page_config(page_title="AI Intelligence · MI Dashboard", page_icon="🧠", layout="wide")
inject_css()

df = load_data()
filtered = render_global_filters(df)

page_header("🧠 AI Intelligence", "Automated summary of the currently selected data — grounded only in computed statistics")

banner(
    "This summary is generated by filling a template with statistics computed directly from the currently "
    "selected data. It does not call an external AI/LLM service and cannot include facts beyond what is shown "
    "elsewhere in this dashboard.",
    kind="warning",
)

if filtered.empty:
    st.warning("No events match the current filters.")
    st.stop()

if st.button("🧠 Generate Intelligence Summary", type="primary"):
    with st.spinner("Compiling summary from selected-data statistics..."):
        result = generate_summary(filtered)
    st.markdown("<div class='section-card'>" + result["text"].replace("\n", "<br>") + "</div>", unsafe_allow_html=True)

    with st.expander("📋 Underlying statistics used in this summary"):
        st.json(result["stats"])
else:
    st.info("Click the button above to generate a summary of the currently filtered dataset.")
